import "@/node_modules/react-modal-video/css/modal-video.css";
import "../public/assets/css/bootstrap.css";
import "../public/assets/css/color.css";
import "../public/assets/css/style.css";
import "swiper/css";
// import "swiper/css/navigation"
import "swiper/css/pagination";
import "swiper/css/free-mode";
import { poppins } from "@/lib/font";
export const metadata = {
  title: "Check Dental Warranty",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable}`}>
      <link rel="icon" href="assets/images/favicon.ico" sizes="" />
      <body>{children}</body>
    </html>
  );
}
